### ISSUE TITLE
<HIGH> Cell Code Area gets overwritten by stacktrace 

### ISSUE THREAD

**Issue by kimo** [PySheets/pysheets#100]
if an error cell is visited, its code gets replaced by stack trace during exit.  Detailed description is in the  video below. @laffra  @sangramsingh-kss  

https://github.com/user-attachments/assets/888aa583-e619-4219-84e5-b649cab27277

**Comment by laffra** [comment]
This is fixed in https://github.com/PySheets/pysheets/commit/352aa291c8715a8fe89e4d18059abf494711fcac

**Comment by kimo** [comment]
Fix Verified at the commit 0f0beb861442151741ab3be0e5d5601477f73055
