### ISSUE TITLE
<HIGH>pandas.read_csv doesn't work in pyodide, but works in desktop python

### ISSUE THREAD

**Issue by kimo** [PySheets/pysheets#102]
Below code errors at read_csv line in pysheets. @sangramsingh-kss  can you take a look. @laffra  fyi.

```
=
# This code was generated by an AI. Please check it for errors.

import pandas as pd

url = 'https://data.ca.gov/dataset/2a5f872d-f7fe-49f2-9581-8f1b17ce5b90/resource/a25e76f7-ec1a-403e-8e9c-ccba492c2fe8/download/ces_1990-2001_monthly_2024627.csv'

df = pd.read_csv(url, nrows=5)

# Display the first few rows of the DataFrame
print(df.head())

# Display basic information about the DataFrame
print(df.info())

# df

```

this is the pysheets issue #101

**Comment by kimo** [comment]
It appears that **pysheets.load_sheet(url)** is the API. Hence closing this and 101 as well. 

@laffra  @sangramsingh-kss

**Comment by laffra** [comment]
I wanted to make this work, so I did fix it and reopened the issue. Please try and see if you can use pandas.read_csv. It should work now.

**Comment by laffra** [comment]
![Screenshot 2024-10-27 222912](https://github.com/user-attachments/assets/4830bb2f-69e3-4bbb-bff6-ebcb8d3eb80f)

**Comment by laffra** [comment]
As an aside. The CSV you originally loaded is around 65MB and take quite a while to load, as a result.

![Screenshot 2024-10-27 223148](https://github.com/user-attachments/assets/87118b5f-c256-4400-97c6-8bc600c423f2)

**Comment by kimo** [comment]
This issue is closed and duckdb example can be referred.
