### ISSUE TITLE
<HIGH><INTEGRATION>yfinance module not working

### ISSUE THREAD

**Issue by kimo** [PySheets/pysheets#109]
```
= 
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
ticker = "AAPL"
data = yf.Ticker(ticker)
hist = data.history(period="1y")
```

![Screenshot 2024-10-26 at 10 59 13 PM](https://github.com/user-attachments/assets/757b2b3a-2480-44b2-9970-202d8ff1f203)

@laffra @sangramsingh-kss

**Comment by laffra** [comment]
I improved network handling and get a lot further. In worker_patch, you can see how we need to monkey-patch the "requests" package to work in the browser. I also figured out how to capture those hidden error messages in the DevTools Console and show them in PySheets's console directly. All that said, the code now works better, but Yahoo Finance complains we make too many calls, so it stops sending responses. 

![Screenshot 2024-10-27 175552](https://github.com/user-attachments/assets/fd7f875a-bc7a-49cf-9452-c3d4bf7c7111)

**Comment by kimo** [comment]
We are indeed sending 78 requests.

![Screenshot 2024-10-27 at 12 31 09 PM](https://github.com/user-attachments/assets/087764fc-8a2f-4c72-9f16-308715449a21)

**Comment by kimo** [comment]
And Pysheets Console shows that we are only sending 7 calls.

![Screenshot 2024-10-27 at 12 37 40 PM](https://github.com/user-attachments/assets/4b64fe47-ac32-41f9-b587-62c94f61ad51)

**Comment by kimo** [comment]
I hope this won't be a rabbit hole that I would be entering into. But i am going to read the patch_code and try to make sense meanwhile. :worried:

**Comment by kimo** [comment]
This is not a problem of pysheets per say. So closing it as "not planned"
