### ISSUE TITLE
<LOW>Just a little annoying everytime a sheet is loaded. May be harmless

### ISSUE THREAD

**Issue by kimo** [PySheets/pysheets#110]
This appears in the console. 
![Screenshot 2024-10-27 at 12 01 03 PM 2](https://github.com/user-attachments/assets/e753367a-7257-404c-9378-3d3e5d7cce1f)

@laffra @sangramsingh-kss

**Comment by laffra** [comment]
I was working on this exactly when you opened this issue :-)

This is now fixed. It annoyed me as well.

**Comment by kimo** [comment]
Fixed.
