### ISSUE TITLE
Should be able to import the PDF's (Or suggest quicker way's of doing this)

### ISSUE THREAD

**Issue by kimo** [PySheets/pysheets#85]
Eg:

I am unable to Import data from this this URL.

https://labormarketinfo.edd.ca.gov/file/lfmonth/countyur-400c.pdf

**Comment by laffra** [comment]
Not sure if this is a PySheets issue. How would you do this in "regular" Python?

**Comment by kimo** [comment]
This is true. This is not a pysheets issue. But I will check if the code works in pysheets and then will close or keep this open.

**Comment by kimo** [comment]
Non-Issue
