### ISSUE TITLE
Practice 01 : Hurricane and tropical storm counts for 2005-2015. 

### ISSUE THREAD

**Issue by kimo** [PySheets/pysheets#87]
Data comes from here. https://people.sc.fsu.edu/~jburkardt/data/csv/csv.html
**Hurricane Data** : https://people.sc.fsu.edu/~jburkardt/data/csv/hurricanes.csv

![Screenshot 2024-09-28 at 8 08 04 AM](https://github.com/user-attachments/assets/7b958273-0e62-4ccb-8509-81fb7f50f30e)

**Comment by laffra** [comment]
This is cool. Did this work as expected?

**Comment by kimo** [comment]
Yes. This worked as expected.
