### ISSUE TITLE
Create WebDriver TestSuite for Tutorial.py

### ISSUE THREAD

**Issue by kimo** [PySheets/pysheets#95]
Placeholder,

Given a module/add-on,  with or without AI tokens the user should be able to create the housekeeping integration tests for the CI/CD pipeline.

@sangramsingh-kss

**Comment by laffra** [comment]
FYI: We are already running Playwright tests. See https://github.com/PySheets/pysheets/actions/workflows/playwright.yml

**Comment by kimo** [comment]
Closed as alternative working approach already exists.
