### ISSUE TITLE
<MEDIUM> Code Work Area Is Not Visible Until DOM Shake

### ISSUE THREAD

**Issue by kimo** [PySheets/pysheets#99]
The detailed description is in the below video link.

@laffra  @sangramsingh-kss 

https://github.com/user-attachments/assets/304496f4-699d-4542-ba23-b4b86420ea43

**Comment by laffra** [comment]
The layout is not responsive enough. I just barely made things work on narrow layouts. This needs more work, obviously.

**Comment by laffra** [comment]
This was fixed by forcing SplitPanes to lay out their children when they get laid out themselves.

**Comment by kimo** [comment]
Verified at the commit 0f0beb861442151741ab3be0e5d5601477f73055
